### ISSUE TITLE
ffmpegd start failed

### ISSUE THREAD

**Issue by hznupeter** [alfg/ffmpegd#2]
I download the ffmpegd from github,but can't start the serve.
it's always stay waiting for connection  as below
![图片](https://user-images.githubusercontent.com/6317759/173006185-3b96e40f-6b9f-42bf-89e6-93738baed8c8.png)

**Comment by alfg** [comment]
Hey @hznupeter, just checking... do you have https://alfg.github.io/ffmpeg-commander loaded in browser with the `ffmpegd` option enabled?

**Comment by alfg** [comment]
Closing. Feel free to respond with any questions.
